
getwd()
setwd("C:/Users/user/Documents/R")
install.packages("dplyr")
library(dplyr)
universalbank=read.csv("UniversalBank.csv")

factor(universalbank$Experience)
A=with(universalbank,tapply(Age,Experience,mean))
barplot(A,main="Experience의 그룹별 Age의 평균",las=2)

factor(universalbank$Income)
A=with(universalbank,tapply(Mortgage,Income,mean))
barplot(A,main="Income의 그룹별 Mortgag의 평균",las=2)

factor(universalbank$Income)
A=with(universalbank,tapply(CCAvg,Income,mean))
barplot(A,main="Income의 그룹별 CCAvg의 평균",las=2)

factor(universalbank$PersonalLoan)
SelPerLoan=select(universalbank,PersonalLoan)
attach(universalbank)
IncoPerLoan=data.frame(PersonalLoan,Income)
A=tapply(Income,PersonalLoan,mean)
barplot(A,main="개인담보대출 유무에 따른 수입의 평균",ylab="수입",las=2)
detach(universalbank)

FamdataFrame1=data.frame(Family,Income)
NChild=subset(FamdataFrame1,subset=(Family==1|Family==2))
Child=subset(FamdataFrame1,subset=(Family==3|Family==4))
HaveChild1=c(sum(mean(NChild$Income)),sum(mean(Child$Income)))
A=matrix(HaveChild1,nrow=1)
colnames(A)=c("자녀가 없는 가정","자녀가 있는 가정",las=2)
barplot(A,main="자녀 유무에 따른 수입")
barplot(A)

FamdataFrame2=data.frame(Family,CCAvg)
NChild=subset(FamdataFrame2,subset=(Family==1|Family==2))
Child=subset(FamdataFrame2,subset=(Family==3|Family==4))
HaveChild2=c(sum(mean(NChild$CCAvg)),sum(mean(Child$CCAvg)))
B=matrix(HaveChild2,nrow=1)
colnames(B)=c("자녀가 없는 가정","자녀가 있는 가정")
barplot(B,main="자녀 유무에 따른 카드 한달 지출 양")
barplot(B)

twen=subset(universalbank,subset=(Age>=20 & Age<30))
thir=subset(universalbank,subset=(Age>=30 & Age<40))
four=subset(universalbank,subset=(Age>=40 & Age<50))
fift=subset(universalbank,subset=(Age>=50 & Age<60))
sixt=subset(universalbank,subset=(Age>=60 & Age<70))
Ages=c(mean(twen$Mortgage),mean(thir$Mortgage),mean(four$Mortgage),mean(fift$Mortgage),mean(sixt$Mortgage))
MatAge=matrix(Ages,nrow=1)
colnames(MatAge)=c("20대","30대","40대","50대","60대")
barplot(MatAge,main="연령대별 대출")

Ages=c(mean(twen$Family),mean(thir$Family),mean(four$Family),mean(fift$Family),mean(sixt$Family))
FaAge=matrix(Ages,nrow=1)
colnames(FaAge)=c("20대","30대","40대","50대","60대")
barplot(FaAge,main="연령대별 가족구성원 수 평균")

Ages=c(mean(twen$PersonalLoan),mean(thir$PersonalLoan),mean(four$PersonalLoan),mean(fift$PersonalLoan),mean(sixt$PersonalLoan))
PeAge=matrix(Ages,nrow=1)
colnames(PeAge)=c("20대","30대","40대","50대","60대")
barplot(PeAge,main="연령대별 개인융자")

Ages=c(mean(twen$SecuritiesAccount),mean(thir$SecuritiesAccount),mean(four$SecuritiesAccount),mean(fift$SecuritiesAccount),mean(sixt$SecuritiesAccount))
SeAge=matrix(Ages,nrow=1)
colnames(SeAge)=c("20대","30대","40대","50대","60대")
barplot(SeAge,main="연령대별 증권계정")

Ages=c(mean(twen$CreditCard),mean(thir$CreditCard),mean(four$CreditCard),mean(fift$CreditCard),mean(sixt$CreditCard))
CrAge=matrix(Ages,nrow=1)
colnames(CrAge)=c("20대","30대","40대","50대","60대")
barplot(CrAge,main="연령대별 신용카드")

Ages=c(mean(twen$Income),mean(thir$Income),mean(four$Income),mean(fift$Income),mean(sixt$Income))
InAge=matrix(Ages,nrow=1)
colnames(InAge)=c("20대","30대","40대","50대","60대")
barplot(InAge,main="연령대별 수입")
